using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using WhatsUp.Models;

namespace Whatsup.Models
{
    [Table("Users")]
    public partial class User
    {
        //set as Primary key
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //switch on autogenerated
        public int Id { get; set; }

        [Required]
        public string Email { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        public byte[] Salt { get; set; }
        [Required]
        public string UserName { get; set; }
        public DateTime DateCreated { get; set; }

        public User()
        {

        }

        public User(string UserName, string Email, string PasswordHash, byte[] Salt, DateTime DateCreated)
        {
            this.UserName = UserName;
            this.Email = Email;
            this.PasswordHash = PasswordHash;
            this.Salt = Salt;
            this.DateCreated = DateCreated;
        }

        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
    }
}