// <auto-generated />
namespace Whatsup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201710050941038_changeaccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
